name: Version Bump Check Pipeline

on:
    pull_request:
        branches: [ "master" ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Get Version from package.json
        id: package_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Get Version from package-lock.json
        id: package_lock_version
        run: echo "LOCK_VERSION=$(jq -r .version package-lock.json)" >> $GITHUB_ENV

      - name: Check if two versions match
        id: check_tags_matching
        run: |
            if [ -z "$LOCK_VERSION" ] || [ -z "$VERSION" ]; then
            echo "Error: One of the version values is empty. Check package.json and package-lock.json."
            exit 1
            fi

            if [ "$LOCK_VERSION" != "$VERSION" ]; then
            echo "Error: package.json and package-lock.json versions do not match!"
            exit 1
            fi

      - name: Check if Tag Already Exists
        id: check_tag
        run: |
          TAG_EXISTS=$(git ls-remote --tags origin refs/tags/v${VERSION})
          if [ -n "$TAG_EXISTS" ]; then
            echo "Tag v${VERSION} already exists. Exiting."
            exit 1
          fi

